### ISSUE TITLE
Autocomplete by country

### ISSUE THREAD

**Issue by Yamilquery** [eastbayjake/google-locations#27]
How can I limit the search by country?

Thank you

**Comment by eastbayjake** [comment]
Hi @Yamilquery, check out the Google Places [Autocomplete API documentation](https://developers.google.com/maps/documentation/javascript/places-autocomplete). As this repo's documentation notes, any valid `options` key/value pair is a valid key/value pair for the autocomplete method's `options` object. I believe you're looking for `types: '(country)'`.
