### ISSUE TITLE
Get Latitude and longitude from autocomplete

### ISSUE THREAD

**Issue by Yamilquery** [eastbayjake/google-locations#28]
I would like to know if it is possible to obtain the latitude and longitude of an autocomplete

**Comment by eastbayjake** [comment]
Again, please reference the Places documentation ([here](https://developers.google.com/maps/documentation/javascript/places-autocomplete#get_place_information) and [here](https://developers.google.com/maps/documentation/javascript/places-autocomplete#place_autocomplete_service)). You will probably need to fetch latitude/longitude details using the place_id returned by autocomplete.

This library is just a wrapper for the library with some convenience functions -- almost all inputs and outputs mirror the Places API documentation.
